# config/deploy.yml

# Name of your application. Used to uniquely configure containers.
service: gothired-staging

# Name of the container image.
image: gabrielrubens/gothired

# Deploy to these servers.
servers: 
  web:
    - 46.202.173.58
  # Uncomment and adjust the following if you have job servers.
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt.
# (If using Cloudflare, ensure SSL/TLS mode is set to "Full" for CF-to-app encryption.)
proxy:
  ssl: true
  host: staging.gothired.ai  # Will use DOMAIN from your CI/CD; defaults to 'gothired.ai'

# Credentials for your image host.
registry:
  username: gabrielrubens
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers.
env:
  secret:
    - SECRET_KEY_BASE
    - RAILS_MASTER_KEY
    - GEMINI_API_KEY
  clear:
    # Example clear environment variables – adjust as needed.
    SOLID_QUEUE_IN_PUMA: true
    # Additional clear env settings can go here.

# Aliases for common commands.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Persistent storage volume configuration.
volumes:
  - "gothired_storage:/rails/storage"

# Asset bridging configuration.
asset_path: /rails/public/assets

# Image builder configuration.
builder:
  arch: amd64
  args:
    CACHE_BUSTER: "2025-03-14"  # Update this value to force a rebuild when necessary.

# Use a non-root SSH user.
ssh:
  user: deployer

# (Optional) Accessory service configurations can be added below.
# accessories:
#   db:
#     ...